name: test

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Create temporary working directory
        run: mkdir ~/tmp

      - name: Download Hyde/Hyde 
        run: cd ~/tmp && wget https://github.com/caendesilva/hyde-monorepo/zipball/master -O hyde.zip

      - name: Unzip archive
        run: cd ~/tmp && unzip hyde.zip

      - name: Copy archive to root
        run: cp -r ~/tmp/caendesilva-hyde-monorepo-*/* .

      
        
      
