name: Propagate Release

on:
  release:
    types: [published] # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

  workflow_dispatch:

jobs:
  create-hyde-release-draft: # https://docs.github.com/en/rest/releases/releases#create-a-release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        run: "curl -X POST -H \"Accept: application/vnd.github.v3+json\" -H \"Authorization: token ${{ github.token }}\" https://api.github.com/repos/caendesilva/gh-integrations-tests-b/releases -d '{\"tag_name\":\"v1.0.0\",\"target_commitish\":\"master\",\"name\":\"v1.0.0\",\"body\":\"Description of the release\",\"draft\":true,\"prerelease\":false,\"generate_release_notes\":true}'"
