name: Propagate Release

on:
  release:
    types: [published] # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

jobs:
  create-hyde-release-draft: # https://docs.github.com/en/rest/releases/releases#create-a-release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        run: |
          curl --request POST \
          --url https://api.github.com/repos/caendesilva/gh-integrations-tests-b/releases \
          --header 'Authorization: token ${{ secrets.PAT }}' \
          --header 'content-type: application/json' \
          --data '{"tag_name":"${{ github.event.tag_name }}","target_commitish":"master","name":"${{ github.event.tag_name }}","body":"Description of the release","draft":true,"prerelease":false,"generate_release_notes":false}'
          --fail
