# This is a basic workflow to help you get started with Actions

name: test-artifacts

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir covrep
          echo "foo" >> covrep/foo
          echo "bar" >> covrep/bar
          echo "bang" >> covrep/bang

      - name: Upload the report as an artifact
        uses: actions/upload-artifact@v1
        with:
          name: "coverage-report"
          path: "covrep"

  download:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download coverage report artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: coverage-report

      - name: Write run metadata to file
        run: |
          currentDate=`date`
          echo "Report automatically uploaded by GitHub at $currentDate" > coverage-report/report-information.txt
      

      - name: Upload report to GitHub Pages
        uses: cpina/github-action-push-to-another-repository@v1.4.2

        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'coverage-report'
          destination-github-username: 'hydephp'
          destination-repository-name: 'developer-tools'
          target-branch: gh-pages
